### ISSUE TITLE
Filtering / Sorting doesn't work with fetchData

### ISSUE THREAD

**Issue by robjstanley** [spatie/vue-table-component#110]
I'm trying to switch from using hardcoded data array to pulling this from the server with pagination, but then filter and sorting don't work. 

Do filters and sorting need to be applied to the collection on the server? or should this still work as it did before with hardcoded data? #

**Comment by sebastiandedeyne** [comment]
Filters and sorting are expected to happen server side, because if you have 1000 records and only display 100 at a time, users will often expect to be searching through the other 900 to.

If you have a different use case regarding filtering or sorting, create a parent component in which you deal with the data fetching, and pass it on to the table component.
