### ISSUE TITLE
TableComponent.settings is not a function

### ISSUE THREAD

**Issue by nWidart** [spatie/vue-table-component#59]
Hello,

I'm testing to see how this package could fit in asgardcms. However We use http://element.eleme.io/#/en-US/component/table which doesn't seem to be compatible with this package.

In any case, I've followed the docs to add a custom class:

```js
import { TableComponent, TableColumn } from 'vue-table-component';

TableComponent.settings({
    tableClass: 'table',
    filterPlaceholder: 'Filter table…',
    filterNoResults: 'There are no matching rows',
});
```

But this throws the following error:
![image](https://user-images.githubusercontent.com/882397/30478669-40fed276-9a12-11e7-93ba-fbc5db6f6e8e.png)

Thanks,

**Comment by sebastiandedeyne** [comment]
`import { TableComponent } from 'vue-table-component';` imports the Vue component.

`import TableComponent from 'vue-table-component';` imports an object that acts as a Vue plugin and gateway to the settings.

In the second version, you can name your variable whatever you want, so you can import everything at once.

```js
import TableComponentPlugin, { TableComponent, TableColumn } from 'vue-table-component';
```

This isn't often necessary though, since they're generally used in different contexts.

`import TableComponent` should happen somewhere high-level, where you're bootstrapping your application. `import { TableComponent }` should happen where you're actually using the component. If you're only using the component on one spot, there's no need to access the settings because every setting is also available as a prop.

**Comment by nWidart** [comment]
aha ok thank you ! 👍
